# frozen_string_literal: true

source 'https://rubygems.org'

gem 'logger'
gem 'minitest-power_assert'
gem 'rack'
gem 'rack-heartbeat'
gem 'rack-minitest'
gem 'rack-unreloader'
gem 'rackup'
gem 'rake', '>= 13.0.6'
gem 'rexml'
gem 'thin'

